[package]
authors = ["Sridhar Ratnakumar <srid@srid.ca>"]
edition = "2021"
# If you change the name here, you must also do it in flake.nix
name = "ncifinance"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
barter = "0.8.12"
barter-data = "0.6.9"
barter-integration = "0.5.1"


# Logging
tracing = "0.1.36"

# Async
tokio = { version = "1.20.1", features = ["sync"] }
tokio-stream = { version = "0.1.9", features = ["sync"] }
futures = "0.3.21"

# Error
thiserror = "1.0.32"

# SerDe
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.83"

# Persistence
redis = "0.22.2"

# Strategy
ta = "0.5.0"

# Misc
uuid = {version = "1.2.2", features = ["v4", "serde"]}
chrono = {version = "0.4.21", features = ["serde"]}
prettytable-rs = "0.10.0"
parking_lot = "0.12.1"